name: Docker Deploy

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          PRERELEASE: ${{steps.extract_branch.outputs.branch != 'master' && true || false }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publush the Docker image
        run: |
          label=$(date +%s)
          latest_tag="${{steps.extract_branch.outputs.branch == 'master' && '--tag ghcr.io/jeppevinkel/steam-punk:latest' || '--tag ghcr.io/jeppevinkel/steam-punk:latest-dev'}}"
          docker build . --file Dockerfile $latest_tag --tag ghcr.io/jeppevinkel/steam-punk:${{steps.tag.outputs.new_tag}}
          docker push --all-tags ghcr.io/jeppevinkel/steam-punk
      - name: Trigger Dev Container Recreation
        uses: distributhor/workflow-webhook@v3
        if: steps.extract_branch.outputs.branch == 'develop' && env.webhook_url != ''
        env:
          webhook_url: ${{ secrets.CONTAINER_DEV_WEBHOOK }}
      - name: Trigger Prod Container Recreation
        uses: distributhor/workflow-webhook@v3
        if: steps.extract_branch.outputs.branch == 'master' && env.webhook_url != ''
        env:
          webhook_url: ${{ secrets.CONTAINER_PROD_WEBHOOK }}